"""Unified context engine (Phase 5).

Read-only aggregation layer on top of the operational database and the
ADHD module. Produces ``DayContext`` (ambient awareness) and
``LifeContext`` (flexible time-range summary) objects consumed by the
supervisor prompt, planning tools, and (in Phase 8) the ProactiveAgent.

The engine does not own data — every field is derived from domain
tables. Insights are generated by 4 plain if/else rules.
"""

from __future__ import annotations

from datetime import UTC, date, datetime, time, timedelta
from pathlib import Path
from typing import Any
from zoneinfo import ZoneInfo

import aiosqlite
import structlog

from kora_v2.adhd.module import ADHDModule
from kora_v2.adhd.profile import ADHDProfile
from kora_v2.adhd.protocol import EnergySignal
from kora_v2.core.calendar_models import CalendarEntry
from kora_v2.core.models import (
    DayContext,
    EnergyEstimate,
    FocusBlockStatus,
    LifeContext,
    MedicationStatus,
    RoutineStatus,
)
from kora_v2.tools.calendar import _load_entries_between

log = structlog.get_logger(__name__)


# ── Energy estimation ───────────────────────────────────────────────────────


def _estimate_energy(
    signals: list[EnergySignal],
    last_check_in: dict[str, Any] | None,
    now: datetime,
) -> EnergyEstimate:
    """Blend self-report + signals into an ``EnergyEstimate``.

    * Self-reports within 2 hours short-circuit everything.
    * Otherwise, start at latent=0.5 and nudge by each signal's
      ``level_adjustment * confidence``; accumulate confidence via
      noisy-OR with a 0.4 time-of-day baseline floor.
    * Snap latent into 3-bucket level and 3-bucket focus.
    """
    # Self-report short-circuit
    if last_check_in is not None:
        logged_at = last_check_in.get("logged_at")
        if isinstance(logged_at, str):
            try:
                logged_dt = datetime.fromisoformat(logged_at)
            except ValueError:
                logged_dt = None
        else:
            logged_dt = logged_at
        if logged_dt is not None:
            if logged_dt.tzinfo is None:
                logged_dt = logged_dt.replace(tzinfo=UTC)
            if (now - logged_dt) < timedelta(hours=2):
                return EnergyEstimate(
                    level=last_check_in.get("level", "medium"),
                    focus=last_check_in.get("focus") or "normal",
                    confidence=1.0,
                    signals=[
                        f"you said '{last_check_in.get('notes') or last_check_in.get('level')}'"
                    ],
                    last_check_in=logged_dt,
                    is_guess=False,
                )

    latent = 0.5
    confidence = 0.4  # baseline floor
    signal_texts: list[str] = []
    for sig in signals:
        latent += sig.level_adjustment * sig.confidence
        confidence = 1.0 - (1.0 - confidence) * (1.0 - sig.confidence)
        signal_texts.append(sig.description)
    latent = max(0.0, min(1.0, latent))

    level = "low" if latent < 0.33 else "high" if latent > 0.66 else "medium"
    focus = (
        "scattered"
        if latent < 0.25
        else "locked_in"
        if latent > 0.75
        else "normal"
    )

    return EnergyEstimate(
        level=level,  # type: ignore[arg-type]
        focus=focus,  # type: ignore[arg-type]
        confidence=confidence,
        signals=signal_texts,
        last_check_in=None,
        is_guess=True,
    )


# ── MedicationStatus computation ─────────────────────────────────────────────


def _build_medication_status(
    profile: ADHDProfile,
    med_log_rows: list[aiosqlite.Row],
    now: datetime,
    user_tz: ZoneInfo,
) -> MedicationStatus:
    """Cross-reference the profile's schedule with today's log rows."""
    local_today = now.astimezone(user_tz).date()
    taken: list[dict[str, Any]] = []
    pending: list[dict[str, Any]] = []
    missed: list[dict[str, Any]] = []
    grace = timedelta(minutes=30)

    for med in profile.medication_schedule:
        for window in med.windows:
            win_start_local = datetime.combine(
                local_today, window.start, tzinfo=user_tz
            )
            win_end_local = datetime.combine(
                local_today, window.end, tzinfo=user_tz
            )
            win_start = win_start_local.astimezone(UTC)
            win_end = win_end_local.astimezone(UTC)

            match = None
            for row in med_log_rows:
                if str(row["medication_name"]).lower() != med.name.lower():
                    continue
                taken_at_raw = row["taken_at"]
                if isinstance(taken_at_raw, str):
                    try:
                        taken_at = datetime.fromisoformat(taken_at_raw)
                    except ValueError:
                        continue
                else:
                    taken_at = taken_at_raw
                if taken_at.tzinfo is None:
                    taken_at = taken_at.replace(tzinfo=UTC)
                if (win_start - grace) <= taken_at <= (win_end + grace):
                    match = taken_at
                    break

            if match is not None:
                taken.append(
                    {
                        "name": med.name,
                        "taken_at": match.astimezone(user_tz).strftime("%H:%M"),
                        "dose": med.dose,
                    }
                )
            elif now > win_end:
                hours_overdue = (now - win_end).total_seconds() / 3600
                missed.append(
                    {
                        "name": med.name,
                        "window": (
                            f"{window.start.strftime('%H:%M')}"
                            f"-{window.end.strftime('%H:%M')}"
                        ),
                        "hours_overdue": round(hours_overdue, 1),
                    }
                )
            else:
                pending.append(
                    {
                        "name": med.name,
                        "window": (
                            f"{window.start.strftime('%H:%M')}"
                            f"-{window.end.strftime('%H:%M')}"
                        ),
                    }
                )

    return MedicationStatus(taken=taken, pending=pending, missed=missed)


# ── ContextEngine ───────────────────────────────────────────────────────────


class ContextEngine:
    """Aggregates domain data into ``DayContext`` / ``LifeContext``.

    Queries the operational database tables directly (calendar_entries,
    medication_log, meal_log, focus_blocks, routine_sessions, finance_log,
    items, reminders, energy_log). Does not own or modify any of them.
    """

    def __init__(
        self,
        db_path: Path,
        adhd_module: ADHDModule,
        user_tz_name: str = "UTC",
    ) -> None:
        self._db_path = db_path
        self._adhd = adhd_module
        self._user_tz_name = user_tz_name
        try:
            self._user_tz = ZoneInfo(user_tz_name)
        except Exception:
            self._user_tz = ZoneInfo("UTC")

    @property
    def user_tz(self) -> ZoneInfo:
        return self._user_tz

    # ── DayContext ────────────────────────────────────────────────

    async def build_day_context(
        self,
        target_date: date | None = None,
        session_state: dict[str, Any] | None = None,
    ) -> DayContext:
        """Build the ambient day-awareness object."""
        if target_date is None:
            target_date = datetime.now(self._user_tz).date()
        day_name = target_date.strftime("%A")

        now_local = datetime.now(self._user_tz)
        now_utc = datetime.now(UTC)

        # Range for the day in UTC
        day_start_local = datetime.combine(
            target_date, time.min, tzinfo=self._user_tz
        )
        day_end_local = day_start_local + timedelta(days=1)
        day_start = day_start_local.astimezone(UTC)
        day_end = day_end_local.astimezone(UTC)

        async with aiosqlite.connect(str(self._db_path)) as db:
            db.row_factory = aiosqlite.Row

            schedule = await _load_entries_between(db, day_start, day_end)

            med_rows = await self._fetch_rows(
                db,
                "SELECT * FROM medication_log WHERE taken_at >= ? AND taken_at < ?",
                (day_start.isoformat(), day_end.isoformat()),
            )
            meal_rows = await self._fetch_rows(
                db,
                "SELECT * FROM meal_log WHERE logged_at >= ? AND logged_at < ? "
                "ORDER BY logged_at ASC",
                (day_start.isoformat(), day_end.isoformat()),
            )
            focus_rows = await self._fetch_rows(
                db,
                "SELECT * FROM focus_blocks WHERE started_at >= ? AND "
                "started_at < ? ORDER BY started_at ASC",
                (day_start.isoformat(), day_end.isoformat()),
            )
            routine_rows = await self._fetch_rows(
                db,
                "SELECT rs.id, rs.status, r.name FROM routine_sessions rs "
                "JOIN routines r ON r.id = rs.routine_id "
                "WHERE rs.started_at >= ? AND rs.started_at < ?",
                (day_start.isoformat(), day_end.isoformat()),
            )
            finance_rows = await self._fetch_rows(
                db,
                "SELECT * FROM finance_log WHERE logged_at >= ? AND "
                "logged_at < ?",
                (day_start.isoformat(), day_end.isoformat()),
            )
            # `due_date` is stored as a bare ISO date string (YYYY-MM-DD)
            # by `tools.planning.create_item`; an exact match against
            # the target date is the only correct comparison. Range
            # comparisons against full ISO datetimes break lexically
            # (e.g. "2026-04-12" < "2026-04-12T00:00:00+00:00").
            items_rows = await self._fetch_rows(
                db,
                "SELECT id, title, status, priority, due_date, goal_scope "
                "FROM items WHERE status NOT IN ('done','cancelled') "
                "AND due_date = ? "
                "ORDER BY priority ASC",
                (target_date.isoformat(),),
            )
            last_energy = await self._fetch_one(
                db,
                "SELECT * FROM energy_log WHERE source = 'self_report' "
                "ORDER BY logged_at DESC LIMIT 1",
                (),
            )

        medication_status = _build_medication_status(
            self._adhd.profile, med_rows, now_utc, self._user_tz
        )

        meals_logged = [
            {
                "type": r["meal_type"],
                "description": r["description"],
                "logged_at": _local_time_str(r["logged_at"], self._user_tz),
            }
            for r in meal_rows
        ]

        focus_blocks = _build_focus_status(focus_rows, schedule, self._user_tz)
        routine_status = _build_routine_status(routine_rows)

        finance_today: dict[str, Any] | None = None
        if finance_rows:
            total = sum(float(r["amount"]) for r in finance_rows)
            finance_today = {
                "total_spend": round(total, 2),
                "entries": [
                    {
                        "amount": float(r["amount"]),
                        "category": r["category"],
                        "description": r["description"],
                    }
                    for r in finance_rows
                ],
            }

        # Next event + minutes_until_next
        next_event: CalendarEntry | None = None
        minutes_until_next: int | None = None
        for entry in schedule:
            if entry.starts_at > now_utc and entry.kind != "buffer":
                next_event = entry
                minutes_until_next = max(
                    0, int((entry.starts_at - now_utc).total_seconds() // 60)
                )
                break

        # Assemble a minimal context for ADHD signal generation, then
        # call energy_signals with the *local* now so peak/crash windows
        # match the profile's local hours, and pass user_tz so morning
        # meetings are counted in the user's wall-clock frame.
        proxy_ctx = type(
            "_Proxy",
            (),
            {
                "medication_status": medication_status,
                "schedule": schedule,
            },
        )()
        signals = self._adhd.energy_signals(
            proxy_ctx, now=now_local, user_tz=self._user_tz
        )

        last_check_in: dict[str, Any] | None = None
        if last_energy is not None:
            last_check_in = {
                "level": last_energy["level"],
                "focus": last_energy["focus"],
                "notes": last_energy["notes"],
                "logged_at": last_energy["logged_at"],
            }
        energy = _estimate_energy(signals, last_check_in, now_utc)

        # Focus / hyperfocus from session state
        turns_in_topic = (
            int(session_state.get("turns_in_current_topic", 0))
            if session_state
            else 0
        )
        session_duration_min = (
            int(session_state.get("session_duration_min", 0))
            if session_state
            else 0
        )
        focus_state = self._adhd.focus_detection(
            turns_in_topic, session_duration_min
        )

        items_due = [
            {
                "id": r["id"],
                "title": r["title"],
                "status": r["status"],
                "priority": r["priority"],
                "due_date": r["due_date"],
                "goal_scope": r["goal_scope"],
            }
            for r in items_rows
        ]

        plan_status = {
            "planned": sum(1 for r in items_rows if r["status"] == "planned"),
            "in_progress": sum(
                1 for r in items_rows if r["status"] == "in_progress"
            ),
            "completed": sum(1 for r in items_rows if r["status"] == "done"),
            "deferred": sum(1 for r in items_rows if r["status"] == "deferred"),
        }

        check_in_suggestion = self._compute_check_in_suggestion(
            last_check_in, session_duration_min, medication_status, energy
        )

        upcoming_nudges = _collect_upcoming_nudges(schedule, now_utc)

        return DayContext(
            date=target_date,
            day_of_week=day_name,
            schedule=schedule,
            next_event=next_event,
            minutes_until_next=minutes_until_next,
            medication_status=medication_status,
            meals_logged=meals_logged,
            focus_blocks=focus_blocks,
            routine_status=routine_status,
            finance_today=finance_today,
            energy=energy,
            hyperfocus_mode=focus_state.hyperfocus_mode,
            session_duration_min=session_duration_min,
            items_due=items_due,
            plan_status=plan_status,
            check_in_suggestion=check_in_suggestion,
            upcoming_nudges=upcoming_nudges,
        )

    # ── LifeContext ───────────────────────────────────────────────

    async def build_life_context(
        self, since: date, until: date, label: str = ""
    ) -> LifeContext:
        """Aggregate data across a flexible time range."""
        since_dt = datetime.combine(since, time.min, tzinfo=self._user_tz).astimezone(UTC)
        until_dt = datetime.combine(until, time.max, tzinfo=self._user_tz).astimezone(UTC)

        async with aiosqlite.connect(str(self._db_path)) as db:
            db.row_factory = aiosqlite.Row
            med_rows = await self._fetch_rows(
                db,
                "SELECT * FROM medication_log WHERE taken_at >= ? AND "
                "taken_at <= ?",
                (since_dt.isoformat(), until_dt.isoformat()),
            )
            focus_rows = await self._fetch_rows(
                db,
                "SELECT * FROM focus_blocks WHERE started_at >= ? AND "
                "started_at <= ? AND ended_at IS NOT NULL",
                (since_dt.isoformat(), until_dt.isoformat()),
            )
            meal_rows = await self._fetch_rows(
                db,
                "SELECT * FROM meal_log WHERE logged_at >= ? AND logged_at <= ?",
                (since_dt.isoformat(), until_dt.isoformat()),
            )
            routine_rows = await self._fetch_rows(
                db,
                "SELECT rs.status, r.name FROM routine_sessions rs "
                "JOIN routines r ON r.id = rs.routine_id "
                "WHERE rs.started_at >= ? AND rs.started_at <= ?",
                (since_dt.isoformat(), until_dt.isoformat()),
            )
            finance_rows = await self._fetch_rows(
                db,
                "SELECT * FROM finance_log WHERE logged_at >= ? AND "
                "logged_at <= ?",
                (since_dt.isoformat(), until_dt.isoformat()),
            )
            energy_rows = await self._fetch_rows(
                db,
                "SELECT * FROM energy_log WHERE logged_at >= ? AND "
                "logged_at <= ?",
                (since_dt.isoformat(), until_dt.isoformat()),
            )
            items_rows = await self._fetch_rows(
                db,
                "SELECT id, status, goal_scope, created_at FROM items "
                "WHERE created_at >= ? AND created_at <= ?",
                (since_dt.isoformat(), until_dt.isoformat()),
            )

        total_days = max(1, (until - since).days + 1)
        med_adherence = _aggregate_medication_adherence(
            med_rows, self._adhd.profile, total_days
        )
        focus_summary = _aggregate_focus_summary(focus_rows, self._user_tz)
        meals_summary = _aggregate_meals_summary(meal_rows, total_days)
        routine_completion = _aggregate_routine_completion(routine_rows)
        finance_summary = _aggregate_finance_summary(finance_rows)
        energy_trend = _aggregate_energy_trend(energy_rows)
        items_summary = _aggregate_items_summary(items_rows)

        lc = LifeContext(
            since=since,
            until=until,
            label=label or f"{since.isoformat()}..{until.isoformat()}",
            medication_adherence=med_adherence,
            focus_summary=focus_summary,
            routine_completion=routine_completion,
            meals_summary=meals_summary,
            finance_summary=finance_summary,
            energy_trend=energy_trend,
            items_summary=items_summary,
        )
        lc.insights = await self.generate_insights(lc)
        return lc

    # ── Insights (4 rules, rule-based, <10 lines each) ───────────

    async def generate_insights(self, lc: LifeContext) -> list[str]:
        insights: list[str] = []

        # Rule 1: Medication adherence correlation with focus
        rate = lc.medication_adherence.get("rate", 1.0)
        daily_avg = lc.focus_summary.get("daily_avg", 99)
        if rate < 0.7 and daily_avg < 2.0:
            insights.append(
                "Focus has been lower on days you skip doses — worth noting, "
                "no judgment."
            )

        # Rule 2: Meal skip correlation with declining focus
        if (
            "lunch" in lc.meals_summary.get("skipped_patterns", [])
            and lc.focus_summary.get("trend") == "declining"
        ):
            insights.append(
                "You tend to skip lunch on busy days — focus dips those "
                "afternoons."
            )

        # Rule 3: Best weekday by focus hours
        by_weekday = lc.focus_summary.get("by_weekday", {}) or {}
        if by_weekday:
            best_day, best_hours = max(
                by_weekday.items(), key=lambda kv: kv[1], default=(None, 0)
            )
            if best_day and best_hours > 0:
                insights.append(f"{best_day} has been your most productive day.")

        # Rule 4: Routine streak detection
        for routine_name, stats in lc.routine_completion.items():
            if not isinstance(stats, dict):
                continue
            completed = stats.get("completed", 0)
            if completed >= 5:
                total = stats.get("total", 7)
                insights.append(
                    f"Nice streak on {routine_name} — {completed}/{total} days."
                )

        return insights

    # ── Internal helpers ──────────────────────────────────────────

    def _compute_check_in_suggestion(
        self,
        last_check_in: dict[str, Any] | None,
        session_minutes: int,
        med_status: MedicationStatus,
        energy: EnergyEstimate,
    ) -> str | None:
        interval = self._adhd.profile.check_in_interval_minutes
        if last_check_in is not None:
            try:
                logged_dt = datetime.fromisoformat(last_check_in["logged_at"])
                if logged_dt.tzinfo is None:
                    logged_dt = logged_dt.replace(tzinfo=UTC)
                if (datetime.now(UTC) - logged_dt) < timedelta(minutes=interval):
                    return None
            except (ValueError, KeyError):
                pass
        if session_minutes >= 120:
            return (
                f"You've been going for {session_minutes}min — how's your "
                "energy?"
            )
        if med_status.missed:
            first = med_status.missed[0]
            return (
                f"Looks like {first['name']} hasn't been logged for the "
                f"{first['window']} window. How are you feeling?"
            )
        return None

    async def _fetch_rows(
        self,
        db: aiosqlite.Connection,
        sql: str,
        params: tuple[Any, ...],
    ) -> list[aiosqlite.Row]:
        async with db.execute(sql, params) as cur:
            return await cur.fetchall()

    async def _fetch_one(
        self,
        db: aiosqlite.Connection,
        sql: str,
        params: tuple[Any, ...],
    ) -> aiosqlite.Row | None:
        async with db.execute(sql, params) as cur:
            return await cur.fetchone()


# ── Status builders ─────────────────────────────────────────────────────────


def _build_focus_status(
    focus_rows: list[aiosqlite.Row],
    schedule: list[CalendarEntry],
    user_tz: ZoneInfo,
) -> FocusBlockStatus:
    completed: list[dict[str, Any]] = []
    active: dict[str, Any] | None = None
    for r in focus_rows:
        started_at = r["started_at"]
        ended_at = r["ended_at"]
        label = r["label"] or "focus"
        if ended_at is None:
            try:
                started_dt = datetime.fromisoformat(started_at)
                if started_dt.tzinfo is None:
                    started_dt = started_dt.replace(tzinfo=UTC)
                elapsed = int(
                    (datetime.now(UTC) - started_dt).total_seconds() / 60
                )
            except (ValueError, TypeError):
                elapsed = 0
            active = {
                "label": label,
                "started_at": _local_time_str(started_at, user_tz),
                "elapsed_min": elapsed,
            }
        else:
            try:
                started_dt = datetime.fromisoformat(started_at)
                if started_dt.tzinfo is None:
                    started_dt = started_dt.replace(tzinfo=UTC)
                ended_dt = datetime.fromisoformat(ended_at)
                if ended_dt.tzinfo is None:
                    ended_dt = ended_dt.replace(tzinfo=UTC)
                duration = int((ended_dt - started_dt).total_seconds() / 60)
            except (ValueError, TypeError):
                duration = 0
            completed.append({"label": label, "duration_min": duration})

    # Planned focus blocks = calendar_entries kind=focus_block starting later
    now_utc = datetime.now(UTC)
    planned: list[dict[str, Any]] = []
    for entry in schedule:
        if entry.kind != "focus_block" or entry.starts_at <= now_utc:
            continue
        duration = (
            int((entry.ends_at - entry.starts_at).total_seconds() / 60)
            if entry.ends_at
            else 0
        )
        planned.append(
            {
                "label": entry.title,
                "starts_at": entry.starts_at.astimezone(user_tz).strftime(
                    "%H:%M"
                ),
                "duration_min": duration,
            }
        )
    return FocusBlockStatus(completed=completed, active=active, planned=planned)


def _build_routine_status(routine_rows: list[aiosqlite.Row]) -> RoutineStatus:
    by_routine: dict[str, str] = {}
    for r in routine_rows:
        name = r["name"]
        status = r["status"]
        if status == "completed":
            by_routine[name] = "completed"
        elif status == "active":
            by_routine[name] = by_routine.get(name, "in_progress")
        else:
            by_routine.setdefault(name, "not_started")
    return RoutineStatus(by_routine=by_routine)


def _local_time_str(raw: Any, user_tz: ZoneInfo) -> str:
    if raw is None:
        return ""
    if isinstance(raw, str):
        try:
            dt = datetime.fromisoformat(raw)
        except ValueError:
            return raw
    else:
        dt = raw
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=UTC)
    return dt.astimezone(user_tz).strftime("%H:%M")


def _collect_upcoming_nudges(
    schedule: list[CalendarEntry], now_utc: datetime
) -> list[str]:
    nudges: list[str] = []
    for entry in schedule[:5]:
        if entry.starts_at <= now_utc or entry.kind == "buffer":
            continue
        minutes = int((entry.starts_at - now_utc).total_seconds() / 60)
        if minutes > 120:
            continue
        label = entry.title
        if entry.kind == "medication_window":
            label = f"{entry.title} window"
        nudges.append(f"{label} in {minutes}min")
    return nudges


# ── LifeContext aggregators ─────────────────────────────────────────────────


def _aggregate_medication_adherence(
    med_rows: list[aiosqlite.Row],
    profile: ADHDProfile,
    total_days: int,
) -> dict[str, Any]:
    windows_per_day = sum(len(m.windows) for m in profile.medication_schedule)
    expected = max(1, windows_per_day * total_days)
    taken = len(med_rows)
    rate = min(1.0, taken / expected) if expected else 1.0
    return {
        "taken_count": taken,
        "expected_count": expected,
        "rate": round(rate, 2),
        "patterns": [],
    }


def _aggregate_focus_summary(
    focus_rows: list[aiosqlite.Row], user_tz: ZoneInfo
) -> dict[str, Any]:
    total_min = 0
    by_day: dict[str, float] = {}
    by_weekday: dict[str, float] = {}
    for r in focus_rows:
        try:
            start = datetime.fromisoformat(r["started_at"])
            end = datetime.fromisoformat(r["ended_at"])
        except ValueError:
            continue
        if start.tzinfo is None:
            start = start.replace(tzinfo=UTC)
        if end.tzinfo is None:
            end = end.replace(tzinfo=UTC)
        minutes = max(0, (end - start).total_seconds() / 60)
        total_min += int(minutes)
        local_day = start.astimezone(user_tz).date().isoformat()
        by_day[local_day] = by_day.get(local_day, 0) + minutes / 60
        weekday = start.astimezone(user_tz).strftime("%A")
        by_weekday[weekday] = by_weekday.get(weekday, 0) + minutes / 60
    daily_avg = (total_min / 60) / max(1, len(by_day)) if by_day else 0
    best_day: str | None = None
    if by_day:
        best_day = max(by_day.items(), key=lambda kv: kv[1])[0]

    # Trend: compare first half vs second half of the date range
    trend = "stable"
    if len(by_day) >= 2:
        ordered_days = sorted(by_day.items())
        mid = len(ordered_days) // 2
        first_half = ordered_days[:mid] or ordered_days[:1]
        second_half = ordered_days[mid:] or ordered_days[-1:]
        first_avg = sum(v for _, v in first_half) / len(first_half)
        second_avg = sum(v for _, v in second_half) / len(second_half)
        if first_avg > 0:
            if second_avg < first_avg * 0.7:
                trend = "declining"
            elif second_avg > first_avg * 1.3:
                trend = "improving"

    return {
        "total_hours": round(total_min / 60, 1),
        "daily_avg": round(daily_avg, 1),
        "trend": trend,
        "best_day": best_day,
        "by_weekday": {k: round(v, 1) for k, v in by_weekday.items()},
    }


def _aggregate_meals_summary(
    meal_rows: list[aiosqlite.Row], total_days: int
) -> dict[str, Any]:
    by_type: dict[str, int] = {}
    for r in meal_rows:
        t = r["meal_type"] or "meal"
        by_type[t] = by_type.get(t, 0) + 1
    avg_per_day = round(len(meal_rows) / max(1, total_days), 2)
    skipped: list[str] = []
    for t in ("breakfast", "lunch", "dinner"):
        if by_type.get(t, 0) < max(1, total_days // 2):
            skipped.append(t)
    return {
        "avg_per_day": avg_per_day,
        "by_type": by_type,
        "skipped_patterns": skipped,
    }


def _aggregate_routine_completion(
    routine_rows: list[aiosqlite.Row],
) -> dict[str, Any]:
    stats: dict[str, dict[str, int]] = {}
    for r in routine_rows:
        name = r["name"]
        stats.setdefault(name, {"completed": 0, "total": 0})
        stats[name]["total"] += 1
        if r["status"] == "completed":
            stats[name]["completed"] += 1
    return stats


def _aggregate_finance_summary(
    finance_rows: list[aiosqlite.Row],
) -> dict[str, Any] | None:
    if not finance_rows:
        return None
    total = 0.0
    by_category: dict[str, float] = {}
    impulse_count = 0
    impulse_total = 0.0
    for r in finance_rows:
        amt = float(r["amount"])
        total += amt
        cat = r["category"] or "other"
        by_category[cat] = round(by_category.get(cat, 0) + amt, 2)
        if r["is_impulse"]:
            impulse_count += 1
            impulse_total += amt
    return {
        "total_spend": round(total, 2),
        "by_category": by_category,
        "impulse_count": impulse_count,
        "impulse_total": round(impulse_total, 2),
    }


def _aggregate_energy_trend(
    energy_rows: list[aiosqlite.Row],
) -> dict[str, Any]:
    if not energy_rows:
        return {"overall": "unknown"}
    levels = {"low": 1, "medium": 2, "high": 3}
    morning: list[int] = []
    afternoon: list[int] = []
    for r in energy_rows:
        try:
            dt = datetime.fromisoformat(r["logged_at"])
        except ValueError:
            continue
        val = levels.get(r["level"], 2)
        if dt.hour < 12:
            morning.append(val)
        else:
            afternoon.append(val)
    def avg(lst: list[int]) -> float:
        return sum(lst) / len(lst) if lst else 0
    return {
        "overall": "stable",
        "morning_avg": (
            "high" if avg(morning) > 2.3 else "low" if avg(morning) < 1.7 else "medium"
        ),
        "afternoon_avg": (
            "high" if avg(afternoon) > 2.3 else "low" if avg(afternoon) < 1.7 else "medium"
        ),
    }


def _aggregate_items_summary(
    items_rows: list[aiosqlite.Row],
) -> dict[str, Any]:
    completed = sum(1 for r in items_rows if r["status"] == "done")
    deferred = sum(1 for r in items_rows if r["status"] == "deferred")
    created = len(items_rows)
    return {
        "completed": completed,
        "created": created,
        "carried_over": deferred,
        "overdue": 0,
    }


__all__ = ["ContextEngine"]
